data:extend({
	{
		type="item-group",
		name="building-materials",
		order="bm",
		inventory_order="bm",
		icons = {
			{ icon = "__Building_Materials__/graphics/icons/64/pallet.png" },
		},
		icon_size = 64,
	},
	{
		type="item-subgroup",
		name="building-decon",
		group="building-materials",
		order="zz",
	},
	{
		type="item-subgroup",
		name="building-materials-a",
		group="building-materials",
		order="l-a",
	},
	{
		type="item-subgroup",
		name="building-materials-b",
		group="building-materials",
		order="m-b",
	},
	{
		type="item-subgroup",
		name="building-materials-c",
		group="building-materials",
		order="m-c",
	},
	{
		type="item-subgroup",
		name="building-cncs-a",
		group="building-materials",
		order="la-a",
	},
	{
		type="item-subgroup",
		name="building-components-0",
		group="building-materials",
		order="tc-0",
	},
	{
		type="item-subgroup",
		name="building-components-1",
		group="building-materials",
		order="tc-1",
	},
	{
		type="item-subgroup",
		name="building-components-2",
		group="building-materials",
		order="tc-2",
	},
	{
		type="item-subgroup",
		name="building-components-3",
		group="building-materials",
		order="tc-3",
	},
	{
		type="item-subgroup",
		name="building-components-4",
		group="building-materials",
		order="tc-4",
	},
	{
		type="item-subgroup",
		name="building-components-5",
		group="building-materials",
		order="tc-5",
	},
	{
		type="item-subgroup",
		name="building-components-rec-0",
		group="building-materials",
		order="tcr-0",
	},
	{
		type="item-subgroup",
		name="building-components-rec-1",
		group="building-materials",
		order="tcr-1",
	},
	{
		type="item-subgroup",
		name="building-components-rec-2",
		group="building-materials",
		order="tcr-2",
	},
	{
		type="item-subgroup",
		name="building-components-rec-3",
		group="building-materials",
		order="tcr-3",
	},
	{
		type="item-subgroup",
		name="building-components-rec-4",
		group="building-materials",
		order="tcr-4",
	},
	{
		type="item-subgroup",
		name="building-components-rec-5",
		group="building-materials",
		order="tcr-5",
	},
	{
		type="item-subgroup",
		name="building-decons",
		group="building-materials",
		order="td",
	},
	{
		type="item-subgroup",
		name="construction-yards",
		group="building-materials",
		order="a-b",
	},
	{
		type="item-subgroup",
		name="material-packagers",
		group="building-materials",
		order="a-c",
	},
	{
		type="item-subgroup",
		name="machine-shops",
		group="building-materials",
		order="a-a",
	},
	{
		type="item-subgroup",
		name="cnc-designers",
		group="building-materials",
		order="a-d",
	},
	{
		type="item-subgroup",
		name="component-fabricators",
		group="building-materials",
		order="a-e",
	},
	{
		type="recipe-category",
		name="building-decon",
	},
	{
		type="recipe-category",
		name="building-components-0",
	},
	{
		type="recipe-category",
		name="building-components-1",
	},
	{
		type="recipe-category",
		name="building-components-2",
	},
	{
		type="recipe-category",
		name="building-components-3",
	},
	{
		type="recipe-category",
		name="building-components-4",
	},
	{
		type="recipe-category",
		name="building-components-5",
	},
	{
		type="recipe-category",
		name="building-material-components-0",
	},
	{
		type="recipe-category",
		name="building-material-components-1",
	},
	{
		type="recipe-category",
		name="building-material-components-2",
	},
	{
		type="recipe-category",
		name="building-material-components-3",
	},
	{
		type="recipe-category",
		name="building-material-components-4",
	},
	{
		type="recipe-category",
		name="building-material-components-5",
	},
	{
		type="recipe-category",
		name="building-cncs-1",
	},
	{
		type="recipe-category",
		name="building-cncs-2",
	},
	{
		type="recipe-category",
		name="building-cncs-3",
	},
	{
		type="recipe-category",
		name="building-cncs-4",
	},
	{
		type="recipe-category",
		name="building-cncs-5",
	},
	{
		type="recipe-category",
		name="buildings-1",
	},
	{
		type="recipe-category",
		name="buildings-2",
	},
	{
		type="recipe-category",
		name="buildings-3",
	},
	{
		type="recipe-category",
		name="buildings-4",
	},
	{
		type="recipe-category",
		name="buildings-5",
	},
	{
		type="recipe-category",
		name="building-materials-0",
	},
	{
		type="recipe-category",
		name="building-materials-1",
	},
	{
		type="recipe-category",
		name="building-materials-2",
	},
	{
		type="recipe-category",
		name="building-materials-3",
	},
	{
		type="recipe-category",
		name="building-materials-4",
	},
	{
		type="recipe-category",
		name="building-materials-5",
	},
})