local bfc = buildM.updater.bldg_from_components
local skip = buildM.updater.skip_building

skip("barreling-pump")

--[[
bfc({bldg = "burner-ore-crusher", tier = 0, components = {"burner-unit", {"stone-wheel", 2}} })
bfc({bldg = "ore-crusher", components = {{"ore-crusher-a1", 1}, {"ore-crusher-c1", 1}} })
bfc({bldg = "ore-crusher-2", components = {{"ore-crusher-a2", 1}, {"ore-crusher-b1", 1}} })
bfc({bldg = "ore-crusher-3", components = {{"ore-crusher-a2", 1}, {"ore-crusher-b2", 1}} })
bfc({bldg = "ore-crusher-4", components = {{"ore-crusher-a3", 1}, {"ore-crusher-b2", 1}} })
bfc({bldg = "ore-sorting-facility", components = {{"ore-sorting-facility-a1", 1}, {"ore-sorting-facility-c1", 1}} })
bfc({bldg = "ore-sorting-facility-2", components = {{"ore-sorting-facility-a2", 1}, {"ore-sorting-facility-b1", 1}} })
bfc({bldg = "ore-sorting-facility-3", components = {{"ore-sorting-facility-a2", 1}, {"ore-sorting-facility-b2", 1}} })
bfc({bldg = "ore-sorting-facility-4", components = {{"ore-sorting-facility-a3", 1}, {"ore-sorting-facility-b2", 1}} })
bfc({bldg = "ore-floatation-cell", components = {{"ore-floatation-cell-a1", 1}, {"ore-floatation-cell-c1", 1}} })
bfc({bldg = "ore-floatation-cell-2", components = {{"ore-floatation-cell-a2", 1}, {"ore-floatation-cell-b1", 1}} })
bfc({bldg = "ore-floatation-cell-3", components = {{"ore-floatation-cell-a2", 1}, {"ore-floatation-cell-b2", 1}} })
bfc({bldg = "ore-floatation-cell-4", components = {{"ore-floatation-cell-a3", 1}, {"ore-floatation-cell-b2", 1}} })
bfc({bldg = "ore-leaching-plant", components = {{"ore-leaching-plant-a1", 1}, {"ore-leaching-plant-c1", 1}} })
bfc({bldg = "ore-leaching-plant-2", components = {{"ore-leaching-plant-a2", 1}, {"ore-leaching-plant-b1", 1}} })
bfc({bldg = "ore-leaching-plant-3", components = {{"ore-leaching-plant-a2", 1}, {"ore-leaching-plant-b2", 1}} })
bfc({bldg = "ore-leaching-plant-4", components = {{"ore-leaching-plant-a3", 1}, {"ore-leaching-plant-b2", 1}} })
bfc({bldg = "ore-refinery", components = {{"ore-refinery-a1", 1}, {"ore-refinery-c1", 1}} })
bfc({bldg = "ore-refinery-2", components = {{"ore-refinery-a2", 1}, {"ore-refinery-b1", 1}} })
bfc({bldg = "ore-refinery-3", components = {{"ore-refinery-a2", 1}, {"ore-refinery-b2", 1}} })
bfc({bldg = "ore-refinery-4", components = {{"ore-refinery-a3", 1}, {"ore-refinery-b2", 1}} })
bfc({bldg = "ore-powderizer", components = {{"ore-powderizer-a1", 1}, {"ore-powderizer-c1", 1}} })
bfc({bldg = "ore-powderizer-2", components = {{"ore-powderizer-a2", 1}, {"ore-powderizer-b1", 1}} })
bfc({bldg = "ore-powderizer-3", components = {{"ore-powderizer-a2", 1}, {"ore-powderizer-b2", 1}} })
bfc({bldg = "ore-powderizer-4", components = {{"ore-powderizer-a3", 1}, {"ore-powderizer-b2", 1}} })
bfc({bldg = "electro-whinning-cell", components = {{"electro-whinning-cell-a1", 1}, {"electro-whinning-cell-c1", 1}} })
bfc({bldg = "electro-whinning-cell-2", components = {{"electro-whinning-cell-a2", 1}, {"electro-whinning-cell-b1", 1}} })
bfc({bldg = "electro-whinning-cell-3", components = {{"electro-whinning-cell-a2", 1}, {"electro-whinning-cell-b2", 1}} })
bfc({bldg = "electro-whinning-cell-4", components = {{"electro-whinning-cell-a3", 1}, {"electro-whinning-cell-b2", 1}} })


bfc({bldg = "crystallizer", components = {{"crystallizer-a1", 1}, {"crystallizer-c1", 1}} })
bfc({bldg = "crystallizer-2", components = {{"crystallizer-a2", 1}, {"crystallizer-b1", 1}} })
bfc({bldg = "crystallizer-3", components = {{"crystallizer-a2", 1}, {"crystallizer-b2", 1}} })
bfc({bldg = "crystallizer-4", components = {{"crystallizer-a3", 1}, {"crystallizer-b2", 1}} })
bfc({bldg = "filtration-unit", components = {{"filtration-unit-a1", 1}, {"filtration-unit-c1", 1}} })
bfc({bldg = "filtration-unit-2", components = {{"filtration-unit-a2", 1}, {"filtration-unit-b1", 1}} })
bfc({bldg = "filtration-unit-3", components = {{"filtration-unit-a2", 1}, {"filtration-unit-b2", 1}} })
bfc({bldg = "filtration-unit-4", components = {{"filtration-unit-a3", 1}, {"filtration-unit-b2", 1}} })
bfc({bldg = "liquifier", components = {{"liquifier-a1", 1}, {"liquifier-c1", 1}} })
bfc({bldg = "liquifier-2", components = {{"liquifier-a2", 1}, {"liquifier-b1", 1}} })
bfc({bldg = "liquifier-3", components = {{"liquifier-a2", 1}, {"liquifier-b2", 1}} })
bfc({bldg = "liquifier-4", components = {{"liquifier-a3", 1}, {"liquifier-b2", 1}} })
bfc({bldg = "hydro-plant", components = {{"hydro-plant-a1", 1}, {"hydro-plant-c1", 1}} })
bfc({bldg = "hydro-plant-2", components = {{"hydro-plant-a2", 1}, {"hydro-plant-b1", 1}} })
bfc({bldg = "hydro-plant-3", components = {{"hydro-plant-a2", 1}, {"hydro-plant-b2", 1}} })
bfc({bldg = "hydro-plant-4", components = {{"hydro-plant-a3", 1}, {"hydro-plant-b2", 1}} })
bfc({bldg = "salination-plant", components = {{"salination-plant-a1", 1}, {"salination-plant-c1", 1}} })
bfc({bldg = "salination-plant-2", components = {{"salination-plant-a2", 1}, {"salination-plant-b1", 1}} })
bfc({bldg = "salination-plant-3", components = {{"salination-plant-a2", 1}, {"salination-plant-b2", 1}} })
bfc({bldg = "salination-plant-4", components = {{"salination-plant-a3", 1}, {"salination-plant-b2", 1}} })
bfc({bldg = "washing-plant", components = {{"washing-plant-a1", 1}, {"washing-plant-c1", 1}} })
bfc({bldg = "washing-plant-2", components = {{"washing-plant-a2", 1}, {"washing-plant-b1", 1}} })
bfc({bldg = "washing-plant-3", components = {{"washing-plant-a2", 1}, {"washing-plant-b2", 1}} })
bfc({bldg = "washing-plant-4", components = {{"washing-plant-a3", 1}, {"washing-plant-b2", 1}} })
bfc({bldg = "advanced-chemical-plant", components = {{"advanced-chemical-plant-a1", 1}, {"advanced-chemical-plant-c1", 1}} })
bfc({bldg = "advanced-chemical-plant-2", components = {{"advanced-chemical-plant-a2", 1}, {"advanced-chemical-plant-b1", 1}} })
bfc({bldg = "advanced-chemical-plant-3", components = {{"advanced-chemical-plant-a2", 1}, {"advanced-chemical-plant-b2", 1}} })
bfc({bldg = "advanced-chemical-plant-4", components = {{"advanced-chemical-plant-a3", 1}, {"advanced-chemical-plant-b2", 1}} })
bfc({bldg = "angels-electrolyser", components = {{"angels-electrolyser-a1", 1}, {"angels-electrolyser-c1", 1}} })
bfc({bldg = "angels-electrolyser-2", components = {{"angels-electrolyser-a2", 1}, {"angels-electrolyser-b1", 1}} })
bfc({bldg = "angels-electrolyser-3", components = {{"angels-electrolyser-a2", 1}, {"angels-electrolyser-b2", 1}} })
bfc({bldg = "angels-electrolyser-4", components = {{"angels-electrolyser-a3", 1}, {"angels-electrolyser-b2", 1}} })
bfc({bldg = "angels-air-filter", components = {{"angels-air-filter-a1", 1}, {"angels-air-filter-c1", 1}} })
bfc({bldg = "angels-air-filter-2", components = {{"angels-air-filter-a2", 1}, {"angels-air-filter-b1", 1}} })
bfc({bldg = "angels-air-filter-3", components = {{"angels-air-filter-a2", 1}, {"angels-air-filter-b2", 1}} })
bfc({bldg = "angels-air-filter-4", components = {{"angels-air-filter-a3", 1}, {"angels-air-filter-b2", 1}} })
bfc({bldg = "angels-chemical-plant", components = {{"angels-chemical-plant-a1", 1}, {"angels-chemical-plant-c1", 1}} })
bfc({bldg = "angels-chemical-plant-2", components = {{"angels-chemical-plant-a2", 1}, {"angels-chemical-plant-b1", 1}} })
bfc({bldg = "angels-chemical-plant-3", components = {{"angels-chemical-plant-a2", 1}, {"angels-chemical-plant-b2", 1}} })
bfc({bldg = "angels-chemical-plant-4", components = {{"angels-chemical-plant-a3", 1}, {"angels-chemical-plant-b2", 1}} })

bfc({bldg = "induction-furnace", components = {{"induction-furnace-a1", 1}, {"induction-furnace-c1", 1}} })
bfc({bldg = "induction-furnace-2", components = {{"induction-furnace-a2", 1}, {"induction-furnace-b1", 1}} })
bfc({bldg = "induction-furnace-3", components = {{"induction-furnace-a2", 1}, {"induction-furnace-b2", 1}} })
bfc({bldg = "induction-furnace-4", components = {{"induction-furnace-a3", 1}, {"induction-furnace-b2", 1}} })
bfc({bldg = "blast-furnace", components = {{"blast-furnace-a1", 1}, {"blast-furnace-c1", 1}} })
bfc({bldg = "blast-furnace-2", components = {{"blast-furnace-a2", 1}, {"blast-furnace-b1", 1}} })
bfc({bldg = "blast-furnace-3", components = {{"blast-furnace-a2", 1}, {"blast-furnace-b2", 1}} })
bfc({bldg = "blast-furnace-4", components = {{"blast-furnace-a3", 1}, {"blast-furnace-b2", 1}} })
bfc({bldg = "angels-chemical-furnace", components = {{"angels-chemical-furnace-a1", 1}, {"angels-chemical-furnace-c1", 1}} })
bfc({bldg = "angels-chemical-furnace-2", components = {{"angels-chemical-furnace-a2", 1}, {"angels-chemical-furnace-b1", 1}} })
bfc({bldg = "angels-chemical-furnace-3", components = {{"angels-chemical-furnace-a2", 1}, {"angels-chemical-furnace-b2", 1}} })
bfc({bldg = "angels-chemical-furnace-4", components = {{"angels-chemical-furnace-a3", 1}, {"angels-chemical-furnace-b2", 1}} })
bfc({bldg = "casting-machine", components = {{"casting-machine-a1", 1}, {"casting-machine-c1", 1}} })
bfc({bldg = "casting-machine-2", components = {{"casting-machine-a2", 1}, {"casting-machine-b1", 1}} })
bfc({bldg = "casting-machine-3", components = {{"casting-machine-a2", 1}, {"casting-machine-b2", 1}} })
bfc({bldg = "casting-machine-4", components = {{"casting-machine-a3", 1}, {"casting-machine-b2", 1}} })
bfc({bldg = "powder-mixer", components = {{"powder-mixer-a1", 1}, {"powder-mixer-c1", 1}} })
bfc({bldg = "powder-mixer-2", components = {{"powder-mixer-a2", 1}, {"powder-mixer-b1", 1}} })
bfc({bldg = "powder-mixer-3", components = {{"powder-mixer-a2", 1}, {"powder-mixer-b2", 1}} })
bfc({bldg = "powder-mixer-4", components = {{"powder-mixer-a3", 1}, {"powder-mixer-b2", 1}} })
bfc({bldg = "ore-processing-machine", components = {{"ore-processing-machine-a1", 1}, {"ore-processing-machine-c1", 1}} })
bfc({bldg = "ore-processing-machine-2", components = {{"ore-processing-machine-a2", 1}, {"ore-processing-machine-b1", 1}} })
bfc({bldg = "ore-processing-machine-3", components = {{"ore-processing-machine-a2", 1}, {"ore-processing-machine-b2", 1}} })
bfc({bldg = "ore-processing-machine-4", components = {{"ore-processing-machine-a3", 1}, {"ore-processing-machine-b2", 1}} })
bfc({bldg = "pellet-press", components = {{"pellet-press-a1", 1}, {"pellet-press-c1", 1}} })
bfc({bldg = "pellet-press-2", components = {{"pellet-press-a2", 1}, {"pellet-press-b1", 1}} })
bfc({bldg = "pellet-press-3", components = {{"pellet-press-a2", 1}, {"pellet-press-b2", 1}} })
bfc({bldg = "pellet-press-4", components = {{"pellet-press-a3", 1}, {"pellet-press-b2", 1}} })
bfc({bldg = "sintering-oven", components = {{"sintering-oven-a1", 1}, {"sintering-oven-c1", 1}} })
bfc({bldg = "sintering-oven-2", components = {{"sintering-oven-a2", 1}, {"sintering-oven-b1", 1}} })
bfc({bldg = "sintering-oven-3", components = {{"sintering-oven-a2", 1}, {"sintering-oven-b2", 1}} })
bfc({bldg = "sintering-oven-4", components = {{"sintering-oven-a3", 1}, {"sintering-oven-b2", 1}} })
bfc({bldg = "strand-casting-machine", components = {{"strand-casting-machine-a1", 1}, {"strand-casting-machine-c1", 1}} })
bfc({bldg = "strand-casting-machine-2", components = {{"strand-casting-machine-a2", 1}, {"strand-casting-machine-b1", 1}} })
bfc({bldg = "strand-casting-machine-3", components = {{"strand-casting-machine-a2", 1}, {"strand-casting-machine-b2", 1}} })
bfc({bldg = "strand-casting-machine-4", components = {{"strand-casting-machine-a3", 1}, {"strand-casting-machine-b2", 1}} })

bfc({bldg = "gas-refinery-small", components = {{"gas-refinery-small-a1", 1}, {"gas-refinery-small-c1", 1}} })
bfc({bldg = "gas-refinery-small-2", components = {{"gas-refinery-small-a2", 1}, {"gas-refinery-small-b1", 1}} })
bfc({bldg = "gas-refinery-small-3", components = {{"gas-refinery-small-a2", 1}, {"gas-refinery-small-b2", 1}} })
bfc({bldg = "gas-refinery-small-4", components = {{"gas-refinery-small-a3", 1}, {"gas-refinery-small-b2", 1}} })
bfc({bldg = "gas-refinery", components = {{"gas-refinery-a1", 1}, {"gas-refinery-c1", 1}} })
bfc({bldg = "gas-refinery-2", components = {{"gas-refinery-a2", 1}, {"gas-refinery-b1", 1}} })
bfc({bldg = "gas-refinery-3", components = {{"gas-refinery-a2", 1}, {"gas-refinery-b2", 1}} })
bfc({bldg = "gas-refinery-4", components = {{"gas-refinery-a3", 1}, {"gas-refinery-b2", 1}} })
bfc({bldg = "steam-cracker", components = {{"steam-cracker-a1", 1}, {"steam-cracker-c1", 1}} })
bfc({bldg = "steam-cracker-2", components = {{"steam-cracker-a2", 1}, {"steam-cracker-b1", 1}} })
bfc({bldg = "steam-cracker-3", components = {{"steam-cracker-a2", 1}, {"steam-cracker-b2", 1}} })
bfc({bldg = "steam-cracker-4", components = {{"steam-cracker-a3", 1}, {"steam-cracker-b2", 1}} })
bfc({bldg = "separator", components = {{"separator-a1", 1}, {"separator-c1", 1}} })
bfc({bldg = "separator-2", components = {{"separator-a2", 1}, {"separator-b1", 1}} })
bfc({bldg = "separator-3", components = {{"separator-a2", 1}, {"separator-b2", 1}} })
bfc({bldg = "separator-4", components = {{"separator-a3", 1}, {"separator-b2", 1}} })
bfc({bldg = "electric-chemical-mixing-furnace", components = {{"electric-chemical-mixing-furnace-a1", 1}, {"electric-chemical-mixing-furnace-c1", 1}} })
bfc({bldg = "electric-chemical-mixing-furnace-2", components = {{"electric-chemical-mixing-furnace-a2", 1}, {"electric-chemical-mixing-furnace-b1", 1}} })

bfc({bldg = "algea-farm", components = {{"algea-farm-a1", 1}, {"algea-farm-c1", 1}} })
bfc({bldg = "algea-farm-2", components = {{"algea-farm-a2", 1}, {"algea-farm-b1", 1}} })
bfc({bldg = "algea-farm-3", components = {{"algea-farm-a2", 1}, {"algea-farm-b2", 1}} })
bfc({bldg = "algea-farm-4", components = {{"algea-farm-a3", 1}, {"algea-farm-b2", 1}} })

--[[
bfc({bldg = "cooling-tower", components = {}})
bfc({bldg = "clarifier", components = {}})
bfc({bldg = "thermal-extractor", components = {}})
bfc({bldg = "angels-electric-boiler", components = {}})

bfc({bldg = "crop-farm", components = {}})
bfc({bldg = "temperate-farm", components = {}})
bfc({bldg = "desert-farm", components = {}})
bfc({bldg = "angels-alien-farm", components = {}})
bfc({bldg = "swamp-farm", components = {}})
bfc({bldg = "seed-extractor", components = {}})
bfc({bldg = "bio-press", components = {}})
bfc({bldg = "bio-processor", components = {}})
bfc({bldg = "nutrient-extractor", components = {}})
bfc({bldg = "bio-aboretum-temperate", components = {}})
bfc({bldg = "bio-aboretum-swamp", components = {}})
bfc({bldg = "composter", components = {}})
bfc({bldg = "bio-generator-desert-1", components = {}})
bfc({bldg = "bio-generator-swamp-1", components = {}})
bfc({bldg = "bio-generator-temperate-1", components = {}})
bfc({bldg = "bio-arboretum-1", components = {}})
--]]

buildM.updater.skip_building("valve-underflow")
buildM.updater.skip_building("valve-overflow")
buildM.updater.skip_building("valve-converter")
buildM.updater.skip_building("valve-check")
buildM.updater.skip_building("valve-return")